apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  namespace: openshift-marketplace
  name: ibm-etcd-operator-catalog
spec:
  image: icr.io/cpopen/ibm-etcd-operator-catalog@sha256:3a874dfbd5deca48696c75ab6145b85cc91b5c3328652cca5427654cc447688a
  displayName: IBM etcd operator Catalog
  publisher: IBM
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 45m