apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  namespace: openshift-marketplace
  name: ibm-model-train-operator-catalog
spec:
  image: icr.io/cpopen/ibm-model-train-operator-catalog@sha256:d1ba88bacfd2d75402e047aa5783be1e1ab2ca75abab4cb021e4f289b19693b0
  displayName: ibm-model-train-operator-catalog
  publisher: IBM
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 45m