apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  namespace: openshift-marketplace
  name: cloud-native-postgresql-catalog
spec:
  image: icr.io/cpopen/ibm-cpd-cloud-native-postgresql-operator-catalog@sha256:7095e3e919fabea5a27fd21c2ba949ea0bf4a2f44010f1ce01a51830ec61e0bd
  displayName: Cloud Native Postgresql Catalog
  publisher: IBM
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 45m