apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  namespace: openshift-marketplace
  name: cpd-platform
spec:
  image: icr.io/cpopen/ibm-cpd-platform-operator-catalog@sha256:a61ccf8bb15791e45fe830772c896902d9f600325c34e675fb30a23bc904986c
  displayName: Cloud Pak for Data
  publisher: IBM
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 45m