apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  namespace: openshift-marketplace
  name: ibm-watson-gateway-operator-catalog
spec:
  image: icr.io/cpopen/watson-gateway-operator-catalog@sha256:b1665e3267d8435843310b0d90bfd378d4dd7060684c7c2ea7e38ac7be1c5afc
  displayName: IBM Watson Gateway Operator Catalog
  publisher: IBM
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 45m