apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  namespace: openshift-marketplace
  name: ibm-minio-operator-catalog
spec:
  image: icr.io/cpopen/opencontent-minio-operator-catalog@sha256:ca6bb27462ae4e5fc92307ca0dc91775cd585ca4fdf39a2a1b3443fea78b700e
  displayName: IBM Minio Operator Catalog
  publisher: IBM
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 45m