apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  namespace: openshift-marketplace
  name: ibm-rabbitmq-operator-catalog
spec:
  image: icr.io/cpopen/opencontent-rabbitmq-operator-catalog@sha256:24fdb883ae6ec8c0823e60f0aa90992f0bb5bbe554d5d662dd6e9de21be133dc
  displayName: IBM RabbitMQ operator Catalog
  publisher: IBM
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 45m