apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-auditwebhook-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: "IBM Audit Webhook Operator Catalog"
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-auditwebhook-operator-catalog@sha256:ec023bed746f529d1f2781cc4c7e48e1154ba22998fc78854cd76120c914bde3
  updateStrategy:
    registryPoll:
      interval: 45m